server:
    port: 8082

spring:
    application:
        name: Rest-Client

feign:
    httpclient:
        enabled: false
    okhttp:
        enabled: true

#Open api swagger ui
springdoc:
    api-docs:
        path: /api-docs
    swagger-ui:
        persist-authorization: true
        tags-sorter: alpha
        doc-expansion: list  # none | list | full


peer:
    api:
        base-url: http://localhost:8080